### ISSUE TITLE
Developing a universal plugin for Live Activities on Flutter is impractical

### ISSUE THREAD

**Issue by ADiksIT** [istornz/live_activities#7]
I think developing a plugin for Live Activities is impractical because it has to do with the API with which we interact on native side.

1. First, your plugin won't support work with remote push notifications because you save data on flutter side to `UserDefaults`  and when you render the widget you get this information from `UserDefaults`.  Probably you can resolve this problem, see example [https://pub.dev/packages/flutter_live_activities](url)
2. I saw common problems in plugins. You have only one "universal" attributes, that's mean that you have only one widget for this attribute. And it problem you cannot fix, because `ActivityKit` work with types Attributes as Generic. That's means that you need to find ways that help you knows about types of attributes in your native side, and ways that will pass types of attributes to your plugin. It seems impossible, but probably you can find a way to fix that. But you will need to get into the thick of Swift runtime, mangled etc. It will be too hard, but if you resolve this problem, your plugin will be great.

My suggestion for all developers is to write their own plugin to work with Live Activities for their requirements. Because it would be very difficult to make a one-size-fits-all solution

**Comment by istornz** [comment]
Hello thanks for your issue 👍

At first, I used the same way to send data as [https://pub.dev/packages/flutter_live_activities](flutter_live_activities) but it was not conclusive (with this method, you can only send String data and I want to send typed data from Dart code, otherwise this plugin loses its interest 👎 ). So I tried the ```UserDefaults``` over ```App Group``` method which allow us to send typed data **AND** image for example which is pretty cool.

This plugin tries to simplify as much as possible the Flutter part by sending data without converting them as ```String``` (very poor quality of code I think...)

To conclude, I'm agree with you: this is **not very easy** to send Dart data to Swift while trying to keep a maximum of functionality & improve developer experience. I'm working hard to find a better way to solve this problem !

This plugin is under active development. You are welcome to make a PR to improve it 👍 
Thanks 👍
